name: Build binaries

permissions:
    contents: write

on:
    push:
        branches: ['**']
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: 1.24.3
            - name: Build binaries
              run: |
                go version
                mkdir -p bin
                GOOS=windows GOARCH=amd64 go build -trimpath -ldflags "-s -w" -o bin/win-rce-checker.exe .
                GOOS=linux   GOARCH=amd64 go build -trimpath -ldflags "-s -w" -o bin/win-rce-checker .
            - name: Commit and push binaries
              run: |
                git config --global user.name 'GitHub Actions'
                git config --global user.email 'actions@github.com'
                git add bin/
                git commit -m "chore: Updated binaries [skip ci]" || echo "No changes to commit"
                git push